# XDG directory for user-local binaries.
PATH="${HOME}/.local/bin:${PATH}"

# These directories are MacPorts.

if [[ -d /opt/local/libexec/gnubin ]] ; then
  PATH="/opt/local/libexec/gnubin:${PATH}"
fi

if [[ -d /opt/local/sbin ]] ; then
  PATH="/opt/local/sbin:${PATH}"
fi

if [[ -d /opt/local/bin ]] ; then
  PATH="/opt/local/bin:${PATH}"
fi

export PATH

# THIS NEEDS TO HAPPEN AFTER PATH IS SET UP.
source "${XDG_CONFIG_HOME}/xdg/xdg_environment.sh"
