" Begin ~/.config/vim/vimrc

" Due to default sudo configuration on Mac OS X, environment variables from the
" original user will get passed into the root shell and this can lead to the
" non-root user's ~/.config/vim/vimrc being loaded. This workaround checks the
" MacOS user database for the real user's username and home directory and
" corrects things if broken.

if empty($MYVIMRC) | let $MYVIMRC = expand('<sfile>:p') | endif

" XDG Base Directory support

if empty($XDG_CACHE_HOME)  | let $XDG_CACHE_HOME  = $HOME . "/.cache"       | endif
if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME = $HOME . "/.config"      | endif
if empty($XDG_DATA_HOME)   | let $XDG_DATA_HOME   = $HOME . "/.local/share" | endif
if empty($XDG_STATE_HOME)  | let $XDG_STATE_HOME  = $HOME . "/.local/state" | endif

if !has('nvim')
  set runtimepath^=$XDG_CONFIG_HOME/vim
  set runtimepath+=$XDG_DATA_HOME/vim
  set runtimepath+=$XDG_CONFIG_HOME/vim/after

  set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
  set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

  set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p', 0700)
  set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p', 0700)
  set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p', 0700)
  set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p', 0700)
  set viminfofile=$XDG_STATE_HOME/vim/viminfo
endif

let g:netrw_home = $XDG_DATA_HOME . "/vim"
call mkdir($XDG_DATA_HOME . "/vim/spell", 'p', 0700)
call mkdir($XDG_STATE_HOME . "/vim", 'p', 0700)

" Quick and dirty vimrc, organize and edit later

set nocompatible

filetype plugin indent on
syntax enable

set hlsearch
set incsearch
set ignorecase

set smartindent
set autoindent
set expandtab
set tabstop=2
set shiftwidth=2

set textwidth=79
set ruler

" End ~/.config/vim/vimrc
